#!/bin/bash

errors=0
for thisfile in tests/in/*; do
	filename=$(basename "$thisfile" )	
	./Text2table $thisfile out.txt
	 cmp out.txt tests/out/$filename ||(echo "test: $filename") && ((errors+=1))	
done

exit  $errors
